channels:
  announcement:
    test server: 1423015091686735912
  roles:
    test server: 1246466929762238625
    shark squad: 1336429573608574986
  welcome:
    test server: 1246466929762238625
    shark squad: 1400757251278508032
  game:
    test server: 1428887560427409589
    shark squad: 1432337887818682469
  chatting:
    shark squad: 1273780642303180852
    test server: 1066090136451952754
  log:
    shark squad: 1443585446830407703
guild role messages:
  test server:
    colour: 1474800508370686095
    general: 1475302912207880194
    test: 1475304226501431297
  shark squad:
    general: 1432537821352296580
    birthdays: 1432539470334394408
    backpack: 1471587842152071432
    sherpa: 1432541922387562529
    friend: 1459553811604705432
birthday message:
  January: false
  February: true
  March: false
  April: false
  May: false
  June: false
  July: false
  August: false
  September: false
  October: false
  November: false
  December: false
time per loop: 1800
window time: 120
set up done:
  test server: true
  shark squad: true
